name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to Cocoapods
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Publish
        run: pod trunk push --skip-tests
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}